.TH FH-EMBED 8
.SH NAME
fh-embed \- convert flashybrid system to embedded mode
.SH SYNOPSIS
.B fh-embed
.SH DESCRIPTION
fh-embed converts a flashybrid system to embedded mode, by remounting the 
flash read-only, unmounting a supplimental disk, etc.
.SH SEE ALSO
.BR fh-full (8)
.BR fh-update (8)
.BR fh-sync (8)
.SH AUTHOR
Joey Hess <joey@kitenet.net>
