.TH FH-FULL 8
.SH NAME
fh-full \- convert flashybrid system to full mode
.SH SYNOPSIS
.B fh-full
.SH DESCRIPTION
fh-full converts a flashybrid system to a full Debian system, by
mounting a supplimental disk, enabling writes to the flash disk, etc.
.SH SEE ALSO
.BR fh-embed (8)
.BR fh-update (8)
.BR fh-sync (8)
.SH AUTHOR
Joey Hess <joey@kitenet.net>
