.TH FH-SYNC 8
.SH NAME
fh-sync \- remount the root file system as read only, and synchronize all changes to the permanent storage
.SH SYNOPSIS
.B fh-sync
.SH DESCRIPTION
Synchronize the RAM storage of flashybrid with the drive. The machine must be
in embedded mode before the call, and after the call the root filesystem will
be remounted as read-only.

Loosely based on the original init scripts of flashybrid v0.002.

.SH AUTHOR
Diego Iastrubni <diego.iastrubni@xorcom.com>
