.TH FH-UPDATE 8
.SH NAME
fh-update \- let flashybrid know about changes to the system
.SH SYNOPSIS
.B fh-update
.SH DESCRIPTION
fh-update lets flashybrid know about changes made to the system. You should
run this after major changes to the system, such as upgrades or new
software installs. Currently, it does nothing unless you are using partial
directory copies via the /etc/flashybrid/partial config file.
.SH SEE ALSO
.BR fh-full (8)
.BR fh-embed (8)
.SH AUTHOR
Joey Hess <joey@kitenet.net>
