.TH MOUNTRO 8
.SH NAME
mountro \- remount the root file systems as read only
.SH SYNOPSIS
.B mountro
.SH DESCRIPTION
mountro remounts the root filesystem as read only. The script is just a wrapper to a 
normal mount command.

.nf
.B mount -o mount,ro /
.fi

.SH SEE ALSO
.BR fh-sync (8)
.BR mountrw (8)
.SH AUTHOR
Diego Iastrubni <diego.iastrubni@xorcom.com>
